var STORE_DATA_MAP = {
  "mapping_by_asm": {
      "Tiên": ["AEONBT - AEON Bình Tân", "AUCO - Âu Cơ", "CHOA - Cộng Hòa (Số 8)", "CUCHI - Củ Chi", "DIAMOND - Diamond Plaza", "LVKHUONG - Lê Văn Khương - Q12", "LYTT - Lý Tự Trọng", "NGA6 - 03 Nguyễn Trãi", "NGANHTHU - Nguyễn Ảnh Thủ", "NGHUE - Nguyễn Huệ", "NTQ1 - 74 Nguyễn Trãi", "OIKHIEM - Ông Ích Khiêm", "PDL - Phan Đăng Lưu", "PDL2 - Phan Đăng Lưu 2", "PTER - Pasteur", "TAKA - Takashimaya", "TCHINH2 - Trường Chinh 2 - Q12", "VINCOM - Vincom Q.1"],
      "Tín": ["BCDN - BigC Đồng Nai", "BENLUC - Bến Lức", "BHNAQUOC - Biên Hòa - Nguyễn Ái Quốc", "BIENHOA - Biên Hoà", "BINHLONG - Bình Long", "BPHUOC - Bình Phước", "LONGAN - Long An", "LONGKHANH - Long Khánh", "LONGTHANH - Long Thành", "TAMHIEP - Tam Hiệp", "TAYNINH - Tây Ninh", "THUDUC - Thủ Đức", "THUDUC2 - Thủ Đức 2", "VINCOMBH - VinCom Biên Hòa"],
      "Dũng": ["BAOLOC - Bảo Lộc", "CHOA3 - 454 Cộng Hòa", "CMT8 - Cách Mạng Tháng 8", "DAKLAK - Daklak", "DAKLAK2 - Daklak - Nguyễn Tất Thành", "DAKLAK5 - Buôn Hồ", "DAKNONG - ĐẮK NÔNG (Tôn Đức Thắng)", "DALAT - Đà Lạt", "DALAT2 - Đà Lạt 2", "GIALAI - Gia Lai", "KONTUM - Kon Tum (Trần Hưng Đạo)", "LBBICH - Lũy Bán Bích", "PTHIET - Phan Thiết", "QBINH - Quảng Bình", "TCHINH - Trường Chinh"],
      "Linh": ["126_3T2 - 126 Đường 3T2", "185_3T2 - 185 Đường 3T2", "901QT - 901 Quang Trung", "AEONTP - AEON Tân Phú", "CAOTH - Cao Thắng", "GOVAP - Gò Vấp", "HBT - Hai Bà Trưng", "LETRONGTAN - Lê Trọng Tấn", "LOTTEGV - Lotte Mart Gò Vấp", "LQDINH - Nguyên Hồng", "LVS - Lê Văn Sỹ", "NDC - Nguyễn Đình Chiểu", "NGUYENOANH - Nguyễn Oanh", "NTMK - Nguyễn Thị Minh Khai", "NVTROI - Nguyễn Văn Trỗi", "PDP - Phan Đình Phùng", "SO1 - Số 1"],
      "Quân": ["BIGCHUE - Aeon Huế", "CAMRANH - Cam Ranh", "DN - Đà Nẵng (Hoàng Diệu)", "DN2 - Đà Nẵng 2 (Lê Duẩn)", "DN3 - Đà Nẳng 3 - Nguyễn Văn Linh", "DN4 - Vincom Đà Nẵng", "DN5DBP - Đà Nẵng 5 (Điện Biên Phủ )", "HUE2 - Huế 2 (Hùng Vương)", "NHT2 - Nha Trang 2 - Lý Tự Trọng", "NHT3 - Nha Trang 1 - Thái Nguyên", "PHANRANG2 - Phan Rang 2", "PHUYEN - Phú Yên", "QNGAI - Quảng Ngãi", "QUANGTRI - QUẢNG TRỊ", "QUINHON2 - Quy Nhơn - Phan Bội Châu", "QUYNHON - Quy Nhơn - Trần Hưng Đạo", "QUYNHON3 - Quy Nhơn 2 - Lý Thường Kiệt", "TAMKY - Tam Kỳ"],
      "Hương": ["BACLIEU - Bạc Liêu", "BACLIEU2 - Bạc Liêu 2 - Trần Huỳnh", "BENTRE - Bến Tre", "CANTHO3T2 - Cần Thơ 3T2", "CMAU - Cà Mau", "CMAU2 - Cà Mau 2 - Nguyễn Tất Thành", "CTHO - Cần Thơ (NT)", "CTHO2 - Cần Thơ (LTT) - Mậu Thân", "CTHO3 - Cần Thơ (HB)", "CTHO6 - Cần Thơ (Nguyễn Văn Cừ)", "HAUGIANG - Hậu Giang - Q6", "KINHDV - Kinh Dương Vương", "STR - Sóc Trăng", "STR2 - Sóc Trăng 2 - Trần Hưng Đạo", "TRAVINH - Trà Vinh", "VINHLONG - Vĩnh Long", "VINHLONG2 - Vĩnh Long 2 - Phạm Thái Bường"],
      "Nhi": ["APHAUGIANG - An Phước Vị Thanh", "CAOLANH - Cao Lãnh", "CAYLAY - Cai Lậy", "CHAUDOC - Châu Đốc - An Giang", "FLDLTTON - FLD Lý Thánh Tôn - Nha Trang", "HATIEN - Hà Tiên", "HONGNGU - Hồng Ngự", "LONGXUYEN2 - Long xuyên 2", "LONGXUYEN3 - Long Xuyên 3 - (Trần Hưng Đạo)", "LXUYEN - Long Xuyên 1 - Hai Bà Trưng", "MYTHO - Mỹ Tho", "MYTHO2 - Mỹ Tho 2", "RACHGIA3 - Rạch Giá 3", "RGIA - Rạch Giá", "RGIA2 - Rạch Giá 2", "SADEC - AN PHƯỚC SA ĐÉC"],
      "Khôi": ["AEONBD - AEON Bình Dương", "BARIA - Bà Rịa (Nguyễn Hữu Thọ)", "BDUONG - Bình Dương", "CREMALL - Crescent Mall Q7", "DBTRAC - Dương Bá Trạc", "DIANBD - Dĩ An - Bình Dương", "DLBD - Đại Lộ Bình Dương", "FLDBDUONG - FLD Nguyễn Đình Chiểu BD", "KHANHHOI - Khánh Hội", "LOTTEQ7 - Lotte Mart Q7", "NTT - Nguyễn Thị Thập", "PMHNDC - Phú Mỹ Hưng 1 - Nguyễn Đức Cảnh", "PMHNLB - Phú Mỹ Hưng 2 - Nguyễn Lương Bằng", "PMHNVL - Phú Mỹ Hưng 3 - Nguyễn Văn Linh", "VTAU2 - Vũng Tàu 2 - Ba Cu", "VTAU3004 - Vũng Tàu 3 - Đường 30-04", "VTAU4 - Vũng Tàu 1 - Lê Hồng Phong"],
      "Lâm": ["HVPLAZA - Hùng Vương Plaza", "SENSECITY - Sense City", "VANHANH - Vạn Hạnh Mall", "VINCOMLVV - Vincom Lê Văn Việt", "VINCOMQ2 - Vincom Thảo Điền", "VINCOMTD - Vincom Grand Park"]
  },
  "mapping_by_region": {
      "HCM": ["126_3T2 - 126 Đường 3T2", "185_3T2 - 185 Đường 3T2", "901QT - 901 Quang Trung", "AEONBT - AEON Bình Tân", "AEONTP - AEON Tân Phú", "AUCO - Âu Cơ", "CAOTH - Cao Thắng", "CHOA - Cộng Hòa (Số 8)", "CHOA3 - 454 Cộng Hòa", "CMT8 - Cách Mạng Tháng 8", "CREMALL - Crescent Mall Q7", "CUCHI - Củ Chi", "DBTRAC - Dương Bá Trạc", "DIAMOND - Diamond Plaza", "GOVAP - Gò Vấp", "HAUGIANG - Hậu Giang - Q6", "HBT - Hai Bà Trưng", "HVPLAZA - Hùng Vương Plaza", "KHANHHOI - Khánh Hội", "KINHDV - Kinh Dương Vương", "LBBICH - Lũy Bán Bích", "LETRONGTAN - Lê Trọng Tấn", "LOTTEGV - Lotte Mart Gò Vấp", "LOTTEQ7 - Lotte Mart Q7", "LQDINH - Nguyên Hồng", "LVKHUONG - Lê Văn Khương - Q12", "LVS - Lê Văn Sỹ", "LYTT - Lý Tự Trọng", "NDC - Nguyễn Đình Chiểu", "NGA6 - 03 Nguyễn Trãi", "NGANHTHU - Nguyễn Ảnh Thủ", "NGHUE - Nguyễn Huệ", "NGUYENOANH - Nguyễn Oanh", "NTMK - Nguyễn Thị Minh Khai", "NTQ1 - 74 Nguyễn Trãi", "NTT - Nguyễn Thị Thập", "NVTROI - Nguyễn Văn Trỗi", "OIKHIEM - Ông Ích Khiêm", "PDL - Phan Đăng Lưu", "PDL2 - Phan Đăng Lưu 2", "PDP - Phan Đình Phùng", "PMHNDC - Phú Mỹ Hưng 1 - Nguyễn Đức Cảnh", "PMHNLB - Phú Mỹ Hưng 2 - Nguyễn Lương Bằng", "PMHNVL - Phú Mỹ Hưng 3 - Nguyễn Văn Linh", "PTER - Pasteur", "SENSECITY - Sense City", "SO1 - Số 1", "TAKA - Takashimaya", "TCHINH - Trường Chinh", "TCHINH2 - Trường Chinh 2 - Q12", "THUDUC - Thủ Đức", "THUDUC2 - Thủ Đức 2", "VANHANH - Vạn Hạnh Mall", "VINCOM - Vincom Q.1", "VINCOMLVV - Vincom Lê Văn Việt", "VINCOMQ2 - Vincom Thảo Điền", "VINCOMTD - Vincom Grand Park"],
      "Miền Trung- Tây Nguyên": ["BAOLOC - Bảo Lộc", "BIGCHUE - Aeon Huế", "CAMRANH - Cam Ranh", "DAKLAK - Daklak", "DAKLAK2 - Daklak - Nguyễn Tất Thành", "DAKLAK5 - Buôn Hồ", "DAKNONG - ĐẮK NÔNG (Tôn Đức Thắng)", "DALAT - Đà Lạt", "DALAT2 - Đà Lạt 2", "DN - Đà Nẵng (Hoàng Diệu)", "DN2 - Đà Nẵng 2 (Lê Duẩn)", "DN3 - Đà Nẳng 3 - Nguyễn Văn Linh", "DN4 - Vincom Đà Nẵng", "DN5DBP - Đà Nẵng 5 (Điện Biên Phủ )", "FLDLTTON - FLD Lý Thánh Tôn - Nha Trang", "GIALAI - Gia Lai", "HUE2 - Huế 2 (Hùng Vương)", "KONTUM - Kon Tum (Trần Hưng Đạo)", "NHT2 - Nha Trang 2 - Lý Tự Trọng", "NHT3 - Nha Trang 1 - Thái Nguyên", "PHANRANG2 - Phan Rang 2", "PHUYEN - Phú Yên", "PTHIET - Phan Thiết", "QBINH - Quảng Bình", "QNGAI - Quảng Ngãi", "QUANGTRI - QUẢNG TRỊ", "QUINHON2 - Quy Nhơn - Phan Bội Châu", "QUYNHON - Quy Nhơn - Trần Hưng Đạo", "QUYNHON3 - Quy Nhơn 2 - Lý Thường Kiệt", "TAMKY - Tam Kỳ"],
      "Miền Tây": ["APHAUGIANG - An Phước Vị Thanh", "BACLIEU - Bạc Liêu", "BACLIEU2 - Bạc Liêu 2 - Trần Huỳnh", "BENLUC - Bến Lức", "BENTRE - Bến Tre", "CANTHO3T2 - Cần Thơ 3T2", "CAOLANH - Cao Lãnh", "CAYLAY - Cai Lậy", "CHAUDOC - Châu Đốc - An Giang", "CMAU - Cà Mau", "CMAU2 - Cà Mau 2 - Nguyễn Tất Thành", "CTHO - Cần Thơ (NT)", "CTHO2 - Cần Thơ (LTT) - Mậu Thân", "CTHO3 - Cần Thơ (HB)", "CTHO6 - Cần Thơ (Nguyễn Văn Cừ)", "HATIEN - Hà Tiên", "HONGNGU - Hồng Ngự", "LONGAN - Long An", "LONGXUYEN2 - Long xuyên 2", "LONGXUYEN3 - Long Xuyên 3 - (Trần Hưng Đạo)", "LXUYEN - Long Xuyên 1 - Hai Bà Trưng", "MYTHO - Mỹ Tho", "MYTHO2 - Mỹ Tho 2", "RACHGIA3 - Rạch Giá 3", "RGIA - Rạch Giá", "RGIA2 - Rạch Giá 2", "SADEC - AN PHƯỚC SA ĐÉC", "STR - Sóc Trăng", "STR2 - Sóc Trăng 2 - Trần Hưng Đạo", "TRAVINH - Trà Vinh", "VINHLONG - Vĩnh Long", "VINHLONG2 - Vĩnh Long 2 - Phạm Thái Bường"],
      "Miền Đông": ["AEONBD - AEON Bình Dương", "BARIA - Bà Rịa (Nguyễn Hữu Thọ)", "BCDN - BigC Đồng Nai", "BDUONG - Bình Dương", "BHNAQUOC - Biên Hòa - Nguyễn Ái Quốc", "BIENHOA - Biên Hoà", "BINHLONG - Bình Long", "BPHUOC - Bình Phước", "DIANBD - Dĩ An - Bình Dương", "DLBD - Đại Lộ Bình Dương", "FLDBDUONG - FLD Nguyễn Đình Chiểu BD", "LONGKHANH - Long Khánh", "LONGTHANH - Long Thành", "TAMHIEP - Tam Hiệp", "TAYNINH - Tây Ninh", "VINCOMBH - VinCom Biên Hòa", "VTAU2 - Vũng Tàu 2 - Ba Cu", "VTAU3004 - Vũng Tàu 3 - Đường 30-04", "VTAU4 - Vũng Tàu 1 - Lê Hồng Phong"]
  }
};